import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :burpee_trainer, BurpeeTrainerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :burpee_trainer, BurpeeTrainerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Keep production diagnostics in a bounded jail-local file. The release runs
# in daemon mode, so redirecting its launcher does not capture runtime logs.
config :logger, level: :info

config :logger, :default_handler,
  config: [
    file: ~c"/var/log/burpee/trainer-runtime.log",
    max_no_bytes: 10_000_000,
    max_no_files: 5
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
